### ISSUE TITLE
Copper ingots compatibility

### ISSUE THREAD

**Issue by purejosh** [Killarexe/Copper-Extension#2]
Hi, I'm the dev of [Pure Copper Tools](https://modrinth.com/mod/purecoppertools), and I had some questions about your mod. 

In my mod, you can craft all four levels of armor and tools from copper ingots and their four stages. I had a user say that they couldn't craft my armor and tools with your ingots, so I was curious if we can work together to fix that. 

On my end, I'll change the recipes to use tags, not items, and that tag will be `c:ingots/copper`, `c:ingots/exposed_copper`, `c:ingots/weathered_copper`, and `c:ingots/oxidized_copper`. This format is correct as shown in the [Common Tags by Fabric](https://wiki.fabricmc.net/community:common_tags). 

On your end, if you also do the same and tag your three stages as those tags above, that'll make it possible to use your copper ingots in the recipes for my armor and tools. 

Thoughts? Look forward to it.

**Comment by Killarexe** [comment]
Hello, I think it's a great idea I'll implement right now!

**Comment by Killarexe** [comment]
I released a new version. Normally I added the tags.
